### ISSUE TITLE
FluSightNetwork forecasts listed as missing in 2017/2018 but are present in the visualization

### ISSUE THREAD

**Issue by nickreich** [BNext-IQT/Viziflu#1]
![image](https://user-images.githubusercontent.com/1280767/50991933-d2e70d00-14e3-11e9-94b1-99ac39f6c07e.png)

**Comment by nickreich** [comment]
I'd hate to think that our team's visualizations were somehow not in the right format or were causing headaches to load into the visualization. :-)

**Comment by gps-iqt-labs** [comment]
Thanks for flagging, Nick -- the label you're referencing has been corrected from FluSightNetwork to FluSightAvg. #f76b50f
